pipeline:
  name: cxcvv
  identifier: cxcvv
  tags: {}
  projectIdentifier: DoNotDelete_Brooke2
  orgIdentifier: Ng_Pipelines_K8s_Organisations
  stages:
    - stage:
        name: ggfgf
        identifier: ggfgf
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: <+input>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
